paths:
  external_data: ''  # Optional path for external data

# list of additional (editable installed) packages to watermark
packages: []

clusters:
  default:
    address: 127.0.0.1:53254
    n_workers: 4
    threads_per_worker: 1
    memory_limit: 8GB

  high_memory:
    address: 127.0.0.1:53255
    n_workers: 1
    threads_per_worker: 1
    memory_limit: 22GB